name: Build Release

on:
  release:
    types: [published]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: Auth GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build OCI Imaage
      run: docker build . --tag ghcr.io/monoxane/vxconnect:${{ github.event.release.tag_name }}
    - name: Push OCI Imaage
      run: docker push ghcr.io/monoxane/vxconnect:${{ github.event.release.tag_name }}